version: '3.8'

services:

  # ----------------------------
  # 1. PRODUCT SERVICE (Node.js + MySQL)
  # ----------------------------

  product-service:
    build: ./product-services
    ports:
      - "${PRODUCT_SERVICE_PORT}:3000"
    env_file:
      - .env
    environment:
      DB_HOST: product-db
      DB_NAME: ${PRODUCT_DB_NAME}
      DB_USER: ${PRODUCT_DB_USER}
      DB_PASSWORD: ${PRODUCT_DB_PASSWORD}
    container_name: product-services
    restart: always
    depends_on:
      - product-db

  product-db:
    image: mysql:8.0.36
    container_name: product-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${PRODUCT_DB_PASSWORD}
      MYSQL_DATABASE: ${PRODUCT_DB_NAME}
    volumes:
      - product-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin  
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: product-db       # Host database
      PMA_USER: root             # User untuk auto login
      PMA_PASSWORD: root         # Password sesuai .env kamu
    depends_on:
      - product-db


  # ----------------------------
  # 2. USER SERVICE (Node.js + PostgreSQL) 
  # ----------------------------

  user-service:
    build: ./user-services
    container_name: user-services
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgres-db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=user_db
      - DB_PORT=5432
    depends_on:
      - postgres-db
    restart: always

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres-db


  # ----------------------------
  # 3. REVIEW SERVICE (Python + MongoDB)
  # ----------------------------

  review-service:
    build: ./review-services
    ports:
      - "5012:5002"
    container_name: review-services
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
    environment:
      MONGO_URI: mongodb://admin:admin123@mongo-db:27017/reviewdb?authSource=admin

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    env_file:
      - .env
    environment:
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db:27017/?authSource=admin
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    restart: always
    depends_on:
      - mongo-db 


  # ==========================================
  # 4. CART SERVICE (PHP + Redis)
  # ==========================================

  cart-service:
    build: ./cart-services
    ports:
      - "8000:8000"
    container_name: cart-services
    restart: always
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
    depends_on:
      - redis-db
    # volumes:
    #   - ./cart-services:/var/www/src

  redis-db:
    image: redis:alpine
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis-db:6379
    ports:
      - "8082:8081" # Akses lewat port 8082
    depends_on:
      - redis-db


volumes:
  product-db-data:
  mongo-data:
  postgres-data:
  redis-data:

# Agar semua container bisa saling komunikasi
# networks:
#   app-network:
#     driver: bridge