services:
  product-service:
    build: ./product-services
    ports: 
      - "${PRODUCT_SERVICE_PORT}:3000"
    env_file:
      - .env
    environment:
      # Pastikan hostnya merujuk ke nama container database
      DB_HOST: product-db  
      DB_NAME: ${PRODUCT_DB_NAME}
      DB_USER: ${PRODUCT_DB_USER}
      DB_PASSWORD: ${PRODUCT_DB_PASSWORD}
    container_name: product-services
    restart: always
    depends_on:
      - product-db
    networks:         # <--- INI YANG HILANG TADI
      - app-network   # <--- WAJIB ADA AGAR BISA KETEMU DATABASE


    # build: ./product-services
    # ports: 
    #   - "${PRODUCT_SERVICE_PORT}:3000"
    # env_file:
    #   - .env
    # environment:
    #   DB_HOST: ${PRODUCT_DB_HOST}
    #   DB_NAME: ${PRODUCT_DB_NAME}
    #   DB_USER: ${PRODUCT_DB_USER}
    #   DB_PASSWORD: ${PRODUCT_DB_PASSWORD}
    # container_name: product-services
    # restart: always
    # depends_on:
    #   - product-db
  
  product-db:
    image: mysql:8.0.36
    container_name: product-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${PRODUCT_DB_PASSWORD}
      MYSQL_DATABASE: ${PRODUCT_DB_NAME}
    volumes:
      - product-db-data:/var/lib/mysql
    networks:
      - app-network

    # image: mysql:8.0.36
    # env_file:
    #   - .env
    # environment:
    #   MYSQL_ROOT_PASSWORD : ${PRODUCT_DB_PASSWORD}
    #   MYSQL_DATABASE : ${PRODUCT_DB_NAME}
    # volumes:
    #   - product-db-data:/var/lib/mysql

  # --- TAMBAHAN PHPMYADMIN ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin  # Nama sesuai request
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: product-db       # Host database
      PMA_USER: root             # User untuk auto login
      PMA_PASSWORD: root         # Password sesuai .env kamu
    depends_on:
      - product-db
    networks:
      - app-network

  # cart-service:
  #   build: ./cart-services
  #   ports:
  #     - "8000:8000"
  #   container_name: cart-services
  #   restart: always

  # review-service:
  #   build: ./review-services
  #   ports:
  #     - "5002:5002"
  #   container_name: review-services
  #   restart: always

volumes:
  product-db-data:

# Agar semua container bisa saling komunikasi
networks:
  app-network:
    driver: bridge

# volumes:
#   product-db-data: